// <auto-generated />
using System;
using HackerStories.DAL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HackerStories.DAL.Migrations
{
    [DbContext(typeof(StoryDbContext))]
    partial class StoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HackerStories.DAL.Entities.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            Image = "/story-images/hacker-story-uniqueId-1.jpg",
                            Time = new DateTime(2024, 2, 23, 16, 8, 32, 236, DateTimeKind.Local).AddTicks(5749),
                            Title = "Title 1",
                            Url = "/story/1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            Image = "/story-images/hacker-story-uniqueId-2.jpg",
                            Time = new DateTime(2024, 2, 23, 16, 8, 32, 236, DateTimeKind.Local).AddTicks(5765),
                            Title = "Title 2",
                            Url = "/story/2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
